MERGE (`oil price`:Instance {name:"oil price"})
MERGE (`supply`:Concept {name:"supply"})
MERGE (`political event`:Concept {name:"political event"})
MERGE (`US election`:Concept {name:"US election"})
MERGE (`geopolitical event`:Concept {name:"geopolitical event"})
MERGE (`war`:Concept {name:"war"})
MERGE (`Russia_Ukraine war`:Instance {name:"Russia_Ukraine war"})
MERGE (`7th october event`:Instance {name:"7th october event"})
MERGE (`oil production`:Instance {name:"oil production"})
MERGE (`oil supply`:Instance {name:"oil supply"})
MERGE (`Middle East conflicts`:Instance {name:"Middle East conflicts"})
MERGE (`demand`:Concept {name:"demand"})
MERGE (`syria revoloution`:Instance {name:"syria revoloution"})
MERGE (`Bab al-Mandab Strait insecurity`:Instance {name:"Bab al-Mandab Strait insecurity"})
MERGE (`market`:Concept {name:"market"})
MERGE (`republican victory`:Instance {name:"republican victory"})
MERGE (`currency`:Concept {name:"currency"})
MERGE (`EUR`:Instance {name:"EUR"})
MERGE (`USD`:Instance {name:"USD"})
MERGE (`oil producer`:Concept {name:"oil producer"})
MERGE (`Russia`:Instance {name:"Russia"})
MERGE (`USA`:Instance {name:"USA"})
MERGE (`Middle East countires`:Concept {name:"Middle East countires"})
MERGE (`2024 Us Election`:Instance {name:"2024 Us Election"})
MERGE (`US market`:Concept {name:"US market"})
MERGE (`gold price`:Instance {name:"gold price"})
MERGE (`inflation`:Instance {name:"inflation"})
MERGE (`currency value`:Instance {name:"currency value"})
MERGE (`forex market`:Instance {name:"forex market"})
MERGE (`stock market`:Instance {name:"stock market"})
MERGE (`international sanction`:Concept {name:"international sanction"})
MERGE (`Tension`:Concept {name:"Tension"})
MERGE (`russia sanctions `:Instance {name:"russia sanctions "})
MERGE (`Europe`:Instance {name:"Europe"})
MERGE (`risk level `:Instance {name:"risk level "})
MERGE (`Iran sanctions`:Instance {name:"Iran sanctions"})
MERGE (`Iran`:Instance {name:"Iran"})
MERGE (`global activity`:Instance {name:"global activity"})
MERGE (`economy growth`:Concept {name:"economy growth"})
MERGE (`china rapid growth`:Instance {name:"china rapid growth"})
MERGE (`India rapid Growth`:Instance {name:"India rapid Growth"})
MERGE (`China`:Instance {name:"China"})
MERGE (`Taiwan`:Instance {name:"Taiwan"})
MERGE (`Asia north esat tensin`:Instance {name:"Asia north esat tensin"})
MERGE (`north america tensions`:Instance {name:"north america tensions"})
MERGE (`overal value`:Instance {name:"overal value"})
MERGE (`country`:Concept {name:"country"})
MERGE (`oil demand`:Instance {name:"oil demand"})
MERGE (`US election`)-[:IS_A]->(`political event`)
MERGE (`war`)-[:IS_A]->(`geopolitical event`)
MERGE (`7th october event`)-[:IS_A]->(`war`)
MERGE (`Russia_Ukraine war`)-[:IS_A]->(`war`)
MERGE (`Middle East conflicts`)-[:CAUSED_BY]->(`7th october event`)
MERGE (`war`)-[:DECREASE]->(`oil production`)
MERGE (`oil supply`)-[:IS_A]->(`supply`)
MERGE (`oil production`)-[:DETERMINE]->(`oil supply`)
MERGE (`demand`)-[:POSITIVELYCORRELATEDWITH]->(`oil price`)
MERGE (`syria revoloution`)-[:CAUSED_BY]->(`7th october event`)
MERGE (`Bab al-Mandab Strait insecurity`)-[:CAUSED_BY]->(`7th october event`)
MERGE (`republican victory`)-[:IS_A]->(`political event`)
MERGE (`EUR`)-[:IS_A]->(`currency`)
MERGE (`USD`)-[:IS_A]->(`currency`)
MERGE (`republican victory`)-[:INCREASEVALUEOF]->(`USD`)
MERGE (`Russia`)-[:IS_A]->(`oil producer`)
MERGE (`USA`)-[:IS_A]->(`oil producer`)
MERGE (`Middle East countires`)-[:IS_A]->(`oil producer`)
MERGE (`Russia`)-[:INVOLVEDIN]->(`Russia_Ukraine war`)
MERGE (`Middle East countires`)-[:INVOLVEDIN]->(`7th october event`)
MERGE (`oil producer`)-[:CONTROL]->(`oil production`)
MERGE (`2024 Us Election`)-[:IS_A]->(`US election`)
MERGE (`US market`)-[:IS_A]->(`market`)
MERGE (`2024 Us Election`)-[:HASNEGATIVEEFFECTON]->(`US market`)
MERGE (`oil price`)-[:POSITIVELYCORRELATEDWITH]->(`inflation`)
MERGE (`inflation`)-[:POSITIVELYCORRELATEDWITH]->(`gold price`)
MERGE (`currency`)-[:HASATTRIBUTE]->(`currency value`)
MERGE (`currency value`)-[:NEGATIVELYCORRELATEDWITH]->(`inflation`)
MERGE (`forex market`)-[:IS_A]->(`US market`)
MERGE (`stock market`)-[:IS_A]->(`US market`)
MERGE (`Russia_Ukraine war`)-[:DECREASEVALUEOF]->(`EUR`)
MERGE (`USD`)-[:POSITIVELYCORRELATEDWITH]->(`US market`)
MERGE (`Bab al-Mandab Strait insecurity`)-[:DECREASEVALUEOF]->(`USD`)
MERGE (`oil supply`)-[:NEGATIVELYCORRELATEDWITH]->(`oil price`)
MERGE (`international sanction`)-[:IS_A]->(`geopolitical event`)
MERGE (`Tension`)-[:IS_A]->(`geopolitical event`)
MERGE (`russia sanctions `)-[:IS_A]->(`international sanction`)
MERGE (`Russia`)-[:ISCOUNTRYSANCTIONEDIN]->(`russia sanctions `)
MERGE (`russia sanctions `)-[:SANCTIONEDBY]->(`USA`)
MERGE (`russia sanctions `)-[:SANCTIONEDBY]->(`Europe`)
MERGE (`risk level `)-[:POSITIVELYCORRELATEDWITH]->(`gold price`)
MERGE (`Iran sanctions`)-[:IS_A]->(`international sanction`)
MERGE (`Iran`)-[:IS_A]->(`Middle East countires`)
MERGE (`Iran`)-[:ISCOUNTRYSANCTIONEDIN]->(`Iran sanctions`)
MERGE (`Iran sanctions`)-[:SANCTIONEDBY]->(`USA`)
MERGE (`international sanction`)-[:INCREASE]->(`risk level `)
MERGE (`china rapid growth`)-[:IS_A]->(`economy growth`)
MERGE (`India rapid Growth`)-[:IS_A]->(`economy growth`)
MERGE (`economy growth`)-[:INCREASE]->(`global activity`)
MERGE (`Asia north esat tensin`)-[:IS_A]->(`Tension`)
MERGE (`north america tensions`)-[:IS_A]->(`Tension`)
MERGE (`Asia north esat tensin`)-[:CAUSEDBY]->(`China`)
MERGE (`Asia north esat tensin`)-[:CAUSEDBY]->(`Taiwan`)
MERGE (`north america tensions`)-[:CAUSEDBY]->(`republican victory`)
MERGE (`market`)-[:HASATTRIBUTE]->(`overal value`)
MERGE (`overal value`)-[:NEGATIVELYCORRELATEDWITH]->(`risk level `)
MERGE (`Asia north esat tensin`)-[:INCREASE]->(`risk level `)
MERGE (`Iran`)-[:IS_A]->(`country`)
MERGE (`USA`)-[:IS_A]->(`country`)
MERGE (`Russia`)-[:IS_A]->(`country`)
MERGE (`China`)-[:IS_A]->(`country`)
MERGE (`Taiwan`)-[:IS_A]->(`country`)
MERGE (`global activity`)-[:DETERMINE]->(`oil demand`)
MERGE (`oil demand`)-[:IS_A]->(`demand`)